// ClaudeParserTests.swift — fixture-driven tests for the Claude JSONL parser.
//
// Fixtures live in Tests/CCGaugeBarTests/Fixtures/. Bundle.module is
// auto-generated by SwiftPM once the testTarget declares resources.

import XCTest
@testable import CCGaugeBar

final class ClaudeParserTests: XCTestCase {

    func fixtureURL(_ name: String) throws -> URL {
        try XCTUnwrap(
            Bundle.module.url(forResource: name, withExtension: "jsonl", subdirectory: "Fixtures"),
            "fixture \(name).jsonl missing — check Package.swift resources block"
        )
    }

    // MARK: - claude-simple.jsonl: user + 2 assistant rows

    func testClaudeSimpleParsesAllRecords() async throws {
        let url = try fixtureURL("claude-simple")
        let parsed = try await ClaudeParser.parseFile(url)

        XCTAssertEqual(parsed.assistant.count, 2)
        XCTAssertEqual(parsed.user.count, 1)
        XCTAssertEqual(parsed.parentLinks.count, 3,
                       "all 3 records contribute to parentLinks (uuid → parentUuid)")
    }

    func testClaudeSimpleAssistantFieldsExtracted() async throws {
        let url = try fixtureURL("claude-simple")
        let parsed = try await ClaudeParser.parseFile(url)
        let a1 = try XCTUnwrap(parsed.assistant.first { $0.uuid == "a1" })

        XCTAssertEqual(a1.source, .claude)
        XCTAssertEqual(a1.model, "claude-sonnet-4-5")
        XCTAssertEqual(a1.requestId, "req1")
        XCTAssertEqual(a1.cwd, "/Users/me/proj")
        XCTAssertEqual(a1.gitBranch, "main")
        XCTAssertEqual(a1.usage.inputTokens, 120)
        XCTAssertEqual(a1.usage.outputTokens, 40)
        XCTAssertEqual(a1.usage.cacheCreationInputTokens, 1500)
        XCTAssertEqual(a1.usage.cacheReadInputTokens, 8000)
        XCTAssertEqual(a1.usage.cacheCreation5m, 1500)
        XCTAssertEqual(a1.usage.cacheCreation1h, 0)
        XCTAssertEqual(a1.toolNames, ["Read"])
        XCTAssertFalse(a1.hasThinking)
        XCTAssertTrue(a1.textPreview.hasPrefix("reading the file"))
    }

    func testClaudeSimpleTotalsMatch() async throws {
        let url = try fixtureURL("claude-simple")
        let parsed = try await ClaudeParser.parseFile(url)

        // Verify the per-record arithmetic the rest of the pipeline relies on:
        // a1 + a2 totals match summing usage by field. Catches silent
        // dropped-field bugs in parseAssistant.
        let totalInput = parsed.assistant.reduce(0) { $0 + $1.usage.inputTokens }
        let totalOutput = parsed.assistant.reduce(0) { $0 + $1.usage.outputTokens }
        let totalCacheRead = parsed.assistant.reduce(0) { $0 + $1.usage.cacheReadInputTokens }
        XCTAssertEqual(totalInput, 200)         // 120 + 80
        XCTAssertEqual(totalOutput, 90)         // 40 + 50
        XCTAssertEqual(totalCacheRead, 17620)   // 8000 + 9620
    }

    // MARK: - claude-synthetic-user.jsonl: isSynthetic detection

    func testSyntheticUsersFlaggedCorrectly() async throws {
        let url = try fixtureURL("claude-synthetic-user")
        let parsed = try await ClaudeParser.parseFile(url)

        XCTAssertEqual(parsed.user.count, 3)

        let sys1 = try XCTUnwrap(parsed.user.first { $0.uuid == "sys1" })
        let sys2 = try XCTUnwrap(parsed.user.first { $0.uuid == "sys2" })
        let real = try XCTUnwrap(parsed.user.first { $0.uuid == "u-real" })

        XCTAssertTrue(sys1.isSynthetic, "<system-reminder> prefix must be flagged synthetic")
        XCTAssertTrue(sys2.isSynthetic, "skill metadata prefix must be flagged synthetic")
        XCTAssertFalse(real.isSynthetic, "regular human prompt must NOT be flagged synthetic")
    }

    func testIsSyntheticUserTextRecognizesAllKnownPrefixes() {
        XCTAssertTrue(ClaudeParser.isSyntheticUserText("<system-reminder>\nfoo\n</system-reminder>"))
        XCTAssertTrue(ClaudeParser.isSyntheticUserText("Base directory for this skill: /tmp"))
        XCTAssertTrue(ClaudeParser.isSyntheticUserText("Caveat: The messages below were generated by a tool"))
        // Leading whitespace tolerated.
        XCTAssertTrue(ClaudeParser.isSyntheticUserText("  <system-reminder>foo</system-reminder>"))

        XCTAssertFalse(ClaudeParser.isSyntheticUserText("hello, normal prompt"))
        XCTAssertFalse(ClaudeParser.isSyntheticUserText(""))
    }
}
